
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_ADDRESS=:8080
      - ADMIN_ADDRESS=:8081
      - JWT_SECRET=your_super_secret_jwt_key
      - REDIS_ADDR=redis:6379
    volumes:
      - "C:\\API\\API\\API:/server" # Mount host directory to /server in the container
    depends_on:
      - redis
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    networks:
      - app-network
    # For non-swarm mode, you can scale using:
    # docker-compose up --scale webapp=3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
    networks:
      - app-network

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
